INSERT INTO PCM_SUPPLIERS(NAME, CODE, ADDRESS) VALUES ('AJAY KUMAR', 'AKD', 'DELHI');
INSERT INTO PCM_SUPPLIERS(NAME, CODE, ADDRESS) VALUES ('SHWETA KUMAR', 'SKD','DELHI');

INSERT INTO PCM_PRODUCT_TYPE (TYPE) VALUES ('MOBILE');
INSERT INTO PCM_PRODUCT_TYPE (TYPE) VALUES ('LAPTOP');

INSERT INTO PCM_PRODUCTS (NAME, COLOR, QUANTITY, TYPE_ID, SUPPLIER_ID) VALUES ('VIVO W123', 'White', 10, 1, 1);
INSERT INTO PCM_PRODUCTS (NAME, COLOR, QUANTITY, TYPE_ID, SUPPLIER_ID) VALUES ('OPPO S123', 'Silver', 15, 1, 1);
INSERT INTO PCM_PRODUCTS (NAME, COLOR, QUANTITY, TYPE_ID, SUPPLIER_ID) VALUES ('HP B123', 'BLACK', 20, 2, 2);
INSERT INTO PCM_PRODUCTS (NAME, COLOR, QUANTITY, TYPE_ID, SUPPLIER_ID) VALUES ('DELL W123', 'White', 25, 2, 2);