CREATE TABLE PCM_SUPPLIERS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(50) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(500),
    CONSTRAINT UK_CODE UNIQUE (CODE)
);

CREATE TABLE PCM_PRODUCT_TYPE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(100) NOT NULL,
    CONSTRAINT UK_TYPE UNIQUE (TYPE)
);

CREATE TABLE PCM_PRODUCTS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	COLOR VARCHAR(50) NOT NULL,
	QUANTITY INT NOT NULL,
	TYPE_ID INT NOT NULL,
	SUPPLIER_ID INT NOT NULL,
	CONSTRAINT FK_TYPE_ID FOREIGN KEY (TYPE_ID) REFERENCES PCM_PRODUCT_TYPE(ID),
	CONSTRAINT FK_SUPPLIER_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES PCM_SUPPLIERS(ID)	
);